# Generated by Django 4.2.10 on 2024-02-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время доставки')),
                ('total_price', models.FloatField(verbose_name='Конечная цена')),
            ],
        ),
        migrations.AddField(
            model_name='customcake',
            name='berries',
            field=models.CharField(blank=True, choices=[('blackberry', 'ежевика'), ('raspberries', 'малина'), ('blueberry', 'голубика'), ('strawberry', 'клубника')], max_length=50, null=True, verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='customcake',
            name='decor',
            field=models.CharField(blank=True, choices=[('pistachios', 'фисташки'), ('meringue', 'безе'), ('hazelnut', 'фундук'), ('pecan', 'пекан'), ('marshmallow', 'маршмеллоу'), ('marzipan', 'марципан')], max_length=50, null=True, verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='customcake',
            name='inscription',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='customcake',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcake',
            name='shape',
            field=models.CharField(choices=[('square', 'квадрат'), ('circle', 'круг'), ('rectangle', 'прямоугольник')], default=1, max_length=50, verbose_name='Форма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcake',
            name='topping',
            field=models.CharField(choices=[('nothing', 'без топпинга'), ('white_souce', 'белый соус'), ('caramel syrup', 'карамельный сироп'), ('maple syrup', 'кленовый сироп'), ('strawberry syrup', 'клубничный сироп'), ('blueberry syrup', 'черничный сироп'), ('milk chocolate', 'молочный шоколад')], default=1, max_length=50, verbose_name='Топпинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customcake',
            name='levels_number',
            field=models.SmallIntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], verbose_name='Количество уровней'),
        ),
        migrations.CreateModel(
            name='OrderBaseCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество тортов в заказе')),
                ('base_cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.basecake', verbose_name='Торт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='base_cakes',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', through='app.OrderBaseCake', to='app.basecake', verbose_name='Торты из меню'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='customcake',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cakes', to='app.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
