# Generated by Django 4.2.10 on 2024-02-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_advertising_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcake',
            name='berries',
            field=models.CharField(blank=True, choices=[('no_berries', 'без ягод'), ('blackberry', 'ежевика'), ('raspberries', 'малина'), ('blueberry', 'голубика'), ('strawberry', 'клубника')], max_length=50, null=True, verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='decor',
            field=models.CharField(blank=True, choices=[('no_decor', 'без декора'), ('pistachios', 'фисташки'), ('meringue', 'безе'), ('hazelnut', 'фундук'), ('pecan', 'пекан'), ('marshmallow', 'маршмеллоу'), ('marzipan', 'марципан')], max_length=50, null=True, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='topping',
            field=models.CharField(choices=[('no_topping', 'без топпинга'), ('white_souce', 'белый соус'), ('caramel_syrup', 'карамельный сироп'), ('maple_syrup', 'кленовый сироп'), ('strawberry_syrup', 'клубничный сироп'), ('blueberry_syrup', 'черничный сироп'), ('milk_chocolate', 'молочный шоколад')], max_length=50, verbose_name='Топпинг'),
        ),
    ]
