# Generated by Django 4.2.10 on 2024-02-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels_number', models.SmallIntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], verbose_name='Количество уровней')),
                ('shape', models.CharField(choices=[('square', 'квадрат'), ('circle', 'круг'), ('rectangle', 'прямоугольник')], max_length=50, verbose_name='Форма')),
                ('topping', models.CharField(choices=[('no_topping', 'без топпинга'), ('white_sauce', 'белый соус'), ('caramel_syrup', 'карамельный сироп'), ('maple_syrup', 'кленовый сироп'), ('strawberry_syrup', 'клубничный сироп'), ('blueberry_syrup', 'черничный сироп'), ('milk_chocolate', 'молочный шоколад')], max_length=50, verbose_name='Топпинг')),
                ('berries', models.CharField(blank=True, choices=[('no_berries', 'без ягод'), ('blackberry', 'ежевика'), ('raspberries', 'малина'), ('blueberry', 'голубика'), ('strawberry', 'клубника')], max_length=50, null=True, verbose_name='Ягоды')),
                ('decor', models.CharField(blank=True, choices=[('no_decor', 'без декора'), ('pistachio', 'фисташки'), ('meringue', 'безе'), ('hazelnut', 'фундук'), ('pecan', 'пекан'), ('marshmallow', 'маршмеллоу'), ('marzipan', 'марципан')], max_length=50, null=True, verbose_name='Декор')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('is_base', models.BooleanField(default=False, verbose_name='Стандартный торт')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.RemoveField(
            model_name='customcake',
            name='client',
        ),
        migrations.RemoveField(
            model_name='customcake',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderbasecake',
            name='base_cake',
        ),
        migrations.RemoveField(
            model_name='orderbasecake',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='base_cakes',
        ),
        migrations.AddField(
            model_name='order',
            name='inscription',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fast_delivery',
            field=models.BooleanField(default=False, verbose_name='Быстрая доставка'),
        ),
        migrations.DeleteModel(
            name='BaseCake',
        ),
        migrations.DeleteModel(
            name='CustomCake',
        ),
        migrations.DeleteModel(
            name='OrderBaseCake',
        ),
        migrations.AddField(
            model_name='order',
            name='cake',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.cake', verbose_name='Торт'),
            preserve_default=False,
        ),
    ]
